Disable zipfile serialization option of torch.save
due to torch versioning, the option is needed when loading the models from manifold
This will fix the error 
raise RuntimeError('New zip file serialization is currently not supported '
RuntimeError: New zip file serialization is currently not supported by Manifold serialization. Please set _use_new_zipfile_serialization=False when doing torch.save